import type { Course, Webinar, Resource } from './types';

export const mockCourses: Course[] = [
  {
    _id: 'course-1',
    title: 'Getting Started with Hallow',
    slug: 'getting-started-with-hallow',
    description: 'A comprehensive introduction to Hallow for parish and school partners. Learn how to set up your partnership, onboard your community, and get the most out of the platform.',
    thumbnail: 'https://images.unsplash.com/photo-1562445735-e038b568a0a0?w=800&q=80',
    category: 'Onboarding',
    featured: true,
    publishedAt: '2024-01-15',
    blocks: [
      {
        _id: 'block-1-1',
        blockType: 'video',
        title: 'Welcome to Your Hallow Partnership',
        slug: 'welcome-to-your-hallow-partnership',
        description: 'An overview of your partnership benefits and what to expect from this course.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 480,
      },
      {
        _id: 'block-1-2',
        blockType: 'file',
        title: 'Partnership Overview & Benefits Guide',
        slug: 'partnership-overview-benefits-guide',
        description: 'A comprehensive PDF covering all the benefits, features, and resources available to Hallow parish partners.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '1.2 MB',
      },
      {
        _id: 'block-1-3',
        blockType: 'video',
        title: 'Setting Up Your Parish Account',
        slug: 'setting-up-your-parish-account',
        description: 'Step-by-step walkthrough of the admin dashboard and account configuration.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 720,
        downloadableAssets: [
          { title: 'Account Setup Checklist', url: '#', fileType: 'PDF' },
        ],
      },
      {
        _id: 'block-1-4',
        blockType: 'file',
        title: 'Account Setup Checklist',
        slug: 'account-setup-checklist',
        description: 'Step-by-step checklist to make sure your parish account is fully configured before inviting your community.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '340 KB',
      },
      {
        _id: 'block-1-5',
        blockType: 'video',
        title: 'Inviting Your Community',
        slug: 'inviting-your-community',
        description: 'How to generate and distribute invite codes to your parishioners or students.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 600,
      },
      {
        _id: 'block-1-6',
        blockType: 'file',
        title: 'Parish Invite Email Templates',
        slug: 'parish-invite-email-templates',
        description: 'Ready-to-send email templates for inviting parishioners to join Hallow. Includes Lent, Advent, and general onboarding versions.',
        fileUrl: '#',
        fileType: 'DOCX',
        fileSize: '58 KB',
      },
      {
        _id: 'block-1-7',
        blockType: 'video',
        title: 'Tracking Engagement & Analytics',
        slug: 'tracking-engagement-and-analytics',
        description: 'Understanding your dashboard metrics and how to measure community engagement.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 840,
      },
    ],
  },
  {
    _id: 'course-2',
    title: 'Leading Prayer in Your Community',
    slug: 'leading-prayer-in-your-community',
    description: 'Practical strategies for parish leaders and teachers to integrate Hallow into daily prayer routines, small groups, and liturgical seasons.',
    thumbnail: 'https://images.unsplash.com/photo-1553340731-5fa0221fde8d?w=800&q=80',
    category: 'Community Leadership',
    featured: true,
    publishedAt: '2024-02-01',
    blocks: [
      {
        _id: 'block-2-1',
        blockType: 'video',
        title: 'Building a Culture of Prayer',
        slug: 'building-a-culture-of-prayer',
        description: 'How to foster consistent prayer habits in your parish or school community.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 900,
      },
      {
        _id: 'block-2-2',
        blockType: 'video',
        title: 'Hallow for Small Groups',
        slug: 'hallow-for-small-groups',
        description: 'Curating Hallow content for Bible studies, faith-sharing groups, and RCIA.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 660,
      },
      {
        _id: 'block-2-3',
        blockType: 'file',
        title: 'Small Group Facilitator Guide',
        slug: 'small-group-facilitator-guide',
        description: 'A structured guide for leading small group prayer sessions using Hallow. Includes discussion questions and session outlines.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '890 KB',
      },
      {
        _id: 'block-2-4',
        blockType: 'video',
        title: 'Seasonal Prayer Campaigns',
        slug: 'seasonal-prayer-campaigns',
        description: 'Running successful Advent, Lent, and other liturgical season challenges.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 780,
      },
    ],
  },
  {
    _id: 'course-3',
    title: 'Hallow in Catholic Schools',
    slug: 'hallow-in-catholic-schools',
    description: 'Designed specifically for Catholic school educators. Integrate Hallow into your daily schedule, religious education classes, and school-wide prayer initiatives.',
    thumbnail: 'https://images.unsplash.com/photo-1658786840545-fff53eee1e86?w=800&q=80',
    category: 'Education',
    featured: false,
    publishedAt: '2024-03-10',
    blocks: [
      {
        _id: 'block-3-1',
        blockType: 'video',
        title: 'Introduction for Educators',
        slug: 'introduction-for-educators',
        description: 'An overview of Hallow\'s school partnership features and the educator dashboard.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 540,
      },
      {
        _id: 'block-3-2',
        blockType: 'video',
        title: 'Classroom Integration Strategies',
        slug: 'classroom-integration-strategies',
        description: 'Practical ways to use Hallow in religion class, homeroom, and beyond.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 840,
      },
      {
        _id: 'block-3-3',
        blockType: 'file',
        title: 'Classroom Integration Guide',
        slug: 'classroom-integration-guide',
        description: 'A printable guide for teachers covering how to integrate Hallow into daily classroom prayer, grades K-12.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '1.1 MB',
      },
      {
        _id: 'block-3-4',
        blockType: 'file',
        title: 'Weekly Prayer Schedule Template',
        slug: 'weekly-prayer-schedule-template',
        description: 'An editable Word document for building a weekly classroom prayer schedule around Hallow content.',
        fileUrl: '#',
        fileType: 'DOCX',
        fileSize: '72 KB',
      },
      {
        _id: 'block-3-5',
        blockType: 'video',
        title: 'Student Engagement & Reporting',
        slug: 'student-engagement-and-reporting',
        description: 'Using the school dashboard to monitor participation and share reports with administration.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 600,
      },
    ],
  },
  {
    _id: 'course-4',
    title: 'Advanced Partnership Features',
    slug: 'advanced-partnership-features',
    description: 'Deep dive into advanced features for experienced partners: custom content channels, bulk user management, API integrations, and white-label options.',
    thumbnail: 'https://images.unsplash.com/photo-1593112038458-246525299766?w=800&q=80',
    category: 'Advanced',
    featured: false,
    publishedAt: '2024-04-05',
    blocks: [
      {
        _id: 'block-4-1',
        blockType: 'video',
        title: 'Custom Content Channels',
        slug: 'custom-content-channels',
        description: 'Create and manage custom prayer channels for your community.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 960,
      },
      {
        _id: 'block-4-2',
        blockType: 'video',
        title: 'Bulk User Management',
        slug: 'bulk-user-management',
        description: 'Import, manage, and organize large numbers of users efficiently.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 720,
      },
      {
        _id: 'block-4-3',
        blockType: 'video',
        title: 'SSO & API Integration',
        slug: 'sso-and-api-integration',
        description: 'Connecting Hallow with your school information system or parish management software.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 1080,
      },
      {
        _id: 'block-4-4',
        blockType: 'file',
        title: 'API Documentation',
        slug: 'api-documentation',
        description: 'Full technical documentation for the Hallow Partner API, including authentication, endpoints, and example requests.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '3.4 MB',
      },
    ],
  },
];

export const mockWebinars: Webinar[] = [
  {
    _id: 'webinar-1',
    title: 'Spring Parish Kickoff: Maximizing Hallow This Lent',
    slug: 'spring-parish-kickoff-maximizing-hallow-this-lent',
    description: 'Join our partnership team for a live walkthrough of the best Hallow content for Lent 2025. We\'ll cover featured meditations, the 40-day challenge, and how to run a parish-wide campaign.',
    thumbnail: 'https://images.unsplash.com/photo-1755643124762-7b69899be8d6?w=800&q=80',
    presenter: 'Maria Santos, Partnership Success Manager',
    scheduledAt: '2026-04-15T18:00:00Z',
    status: 'upcoming',
    registrationUrl: 'https://hallow.com/webinar-register',
    duration: 60,
    tags: ['Lent', 'Parish', 'Seasonal'],
    featured: true,
    spotlight: true,
  },
  {
    _id: 'webinar-2',
    title: 'New Partner Orientation — Q2 2026',
    slug: 'new-partner-orientation-q2-2026',
    description: 'A live onboarding session for partners who joined in the last 90 days. Get your questions answered and connect with other new partners.',
    thumbnail: 'https://images.unsplash.com/photo-1560698831-07984c110e4d?w=800&q=80',
    presenter: 'James O\'Brien, Head of Partner Success',
    scheduledAt: '2026-04-22T19:00:00Z',
    status: 'upcoming',
    registrationUrl: 'https://hallow.com/webinar-register',
    duration: 90,
    tags: ['Onboarding', 'New Partners'],
    featured: false,
  },
  {
    _id: 'webinar-3',
    title: 'Year in Review: Partner Success Stories 2025',
    slug: 'year-in-review-partner-success-stories-2025',
    description: 'Highlights from our top partner communities in 2025 — hear directly from parishes and schools that achieved remarkable growth in prayer engagement.',
    thumbnail: 'https://images.unsplash.com/photo-1676200259384-b2900d8478a3?w=800&q=80',
    presenter: 'Multiple Presenters',
    scheduledAt: '2025-12-10T19:00:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456789',
    duration: 75,
    tags: ['Case Studies', 'Community', 'Annual Review'],
    featured: true,
  },
  {
    _id: 'webinar-4',
    title: 'Advent Planning Workshop',
    slug: 'advent-planning-workshop',
    description: 'Everything you need to run a successful Advent prayer campaign. Templates, best practices, and a live Q&A with the content team.',
    thumbnail: 'https://images.unsplash.com/photo-1763630239158-d032e93d525b?w=800&q=80',
    presenter: 'Fr. Timothy Walsh & Partnership Team',
    scheduledAt: '2025-10-20T18:30:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456790',
    duration: 90,
    tags: ['Advent', 'Seasonal', 'Parish'],
    featured: false,
  },
  {
    _id: 'webinar-5',
    title: 'Hallow for Catholic Schools: Back to School Edition',
    slug: 'hallow-for-catholic-schools-back-to-school',
    description: 'Preparing your school community for a new year of prayer with Hallow. Covers classroom setup, student accounts, and the new educator portal.',
    thumbnail: 'https://images.unsplash.com/photo-1465848059293-208e11dfea17?w=800&q=80',
    presenter: 'Sarah Kim, Education Partnerships Lead',
    scheduledAt: '2025-08-15T17:00:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456791',
    duration: 60,
    tags: ['Schools', 'Education', 'Onboarding'],
    featured: false,
  },
];

export const mockResources: Resource[] = [
  {
    _id: 'resource-1',
    title: 'Partner Welcome Guide',
    slug: 'partner-welcome-guide',
    description: 'Your complete reference for getting started as a Hallow partner. Covers account setup, key contacts, and your first 30 days.',
    category: 'documentation',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-01-10',
    fileType: 'PDF',
  },
  {
    _id: 'resource-2',
    title: 'Parish Bulletin Insert Templates',
    slug: 'parish-bulletin-insert-templates',
    description: 'Ready-to-use bulletin inserts for announcing Hallow to your parishioners. Available in standard bulletin sizes.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-01-20',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-3',
    title: 'Lent 2026 Campaign Kit',
    slug: 'lent-2026-campaign-kit',
    description: 'Complete campaign materials for Lent 2026 including social media graphics, bulletin inserts, email templates, and a promotional video.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2026-01-15',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-4',
    title: 'Hallow x RCIA: A Curriculum Guide',
    slug: 'hallow-rcia-curriculum-guide',
    description: 'A semester-long curriculum guide for RCIA directors incorporating Hallow meditations, Scripture, and prayer practices.',
    category: 'teacher-planning',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-01',
    fileType: 'PDF',
  },
  {
    _id: 'resource-5',
    title: 'Admin Dashboard User Manual',
    slug: 'admin-dashboard-user-manual',
    description: 'Detailed documentation for the partner admin dashboard. Covers user management, analytics, content settings, and billing.',
    category: 'technical-guides',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-02-15',
    fileType: 'PDF',
  },
  {
    _id: 'resource-6',
    title: 'How to Talk About Hallow: Key Messages',
    slug: 'how-to-talk-about-hallow-key-messages',
    description: 'Approved talking points, FAQs, and messaging guidance for introducing Hallow to your community.',
    category: 'educational-content',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-02-01',
    fileType: 'PDF',
  },
  {
    _id: 'resource-7',
    title: 'Classroom Prayer Integration Guide',
    slug: 'classroom-prayer-integration-guide',
    description: 'For Catholic school educators: structured guides for incorporating Hallow into daily classroom prayer routines, grades K-12.',
    category: 'teacher-planning',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-15',
    fileType: 'PDF',
  },
  {
    _id: 'resource-8',
    title: 'API & SSO Integration Documentation',
    slug: 'api-sso-integration-documentation',
    description: 'Technical documentation for connecting Hallow to your school information system (SIS) or parish management software via SSO or API.',
    category: 'technical-guides',
    resourceType: 'link',
    externalUrl: '#',
    featured: false,
    publishedAt: '2024-04-01',
    fileType: 'LINK',
  },
  {
    _id: 'resource-9',
    title: 'Social Media Asset Pack',
    slug: 'social-media-asset-pack',
    description: 'High-resolution social media graphics, story templates, and profile overlays for promoting Hallow on your parish or school accounts.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-01-25',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-10',
    title: 'The Science of Prayer: A Discussion Guide',
    slug: 'science-of-prayer-discussion-guide',
    description: 'Educational resource exploring the research behind prayer and mindfulness. Great for adult faith formation groups and high school theology classes.',
    category: 'educational-content',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-20',
    fileType: 'PDF',
  },
];
