import type { Course, Webinar, Resource } from './types';

export const mockCourses: Course[] = [
  {
    _id: 'course-1',
    title: 'Getting Started with Hallow',
    slug: 'getting-started-with-hallow',
    description: 'A comprehensive introduction to Hallow for parish and school partners. Learn how to set up your partnership, onboard your community, and get the most out of the platform.',
    thumbnail: 'https://images.unsplash.com/photo-1562445735-e038b568a0a0?w=800&q=80',
    category: 'Onboarding',
    featured: true,
    publishedAt: '2024-01-15',
    blocks: [
      // ── Section 1: Your Partnership ──────────────────────────
      {
        _id: 'block-1-1',
        blockType: 'video',
        title: 'Welcome to Your Hallow Partnership',
        slug: 'welcome-to-your-hallow-partnership',
        description: 'An overview of your partnership benefits and what to expect from this course.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 480,
      },
      {
        _id: 'block-1-2',
        blockType: 'file',
        title: 'Partnership Overview & Benefits Guide',
        slug: 'partnership-overview-benefits-guide',
        description: 'A comprehensive PDF covering all the benefits, features, and resources available to Hallow parish partners.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '1.2 MB',
      },
      // ── Section 2: Account Setup ──────────────────────────────
      {
        _id: 'block-1-3',
        blockType: 'video',
        title: 'Setting Up Your Parish Account',
        slug: 'setting-up-your-parish-account',
        description: 'Step-by-step walkthrough of the admin dashboard and account configuration.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 720,
      },
      {
        _id: 'block-1-4',
        blockType: 'file',
        title: 'Account Setup Checklist',
        slug: 'account-setup-checklist',
        description: 'Step-by-step checklist to make sure your parish account is fully configured before inviting your community.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '340 KB',
      },
      {
        _id: 'block-1-5',
        blockType: 'quiz',
        title: 'Check-In: Account Setup',
        slug: 'check-in-account-setup',
        description: 'Make sure you have the account basics down before moving on.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-1-1',
            question: 'What is the recommended first step after your parish account is created?',
            options: [
              'Run a Lent campaign immediately',
              'Set your preferred language',
              'Complete the account setup checklist',
              'Contact your parishioners directly',
            ],
            correctIndex: 2,
            explanation: 'The account setup checklist ensures all your settings are correctly configured before you invite your community.',
          },
          {
            _id: 'q-1-2',
            question: 'Where do you access the partner admin dashboard?',
            options: [
              'Inside the Hallow mobile app under Settings',
              'At partners.hallow.com in your browser',
              'Through the App Store',
              'By emailing parishes@hallow.app for a link',
            ],
            correctIndex: 1,
            explanation: 'The partner admin dashboard is a web-based tool available at partners.hallow.com — separate from the Hallow consumer app.',
          },
        ],
      },
      // ── Section 3: Community Onboarding ──────────────────────
      {
        _id: 'block-1-6',
        blockType: 'video',
        title: 'Inviting Your Community',
        slug: 'inviting-your-community',
        description: 'How to generate and distribute invite codes to your parishioners or students.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 600,
      },
      {
        _id: 'block-1-7',
        blockType: 'file',
        title: 'Parish Invite Email Templates',
        slug: 'parish-invite-email-templates',
        description: 'Ready-to-send email templates for inviting parishioners to join Hallow. Includes Lent, Advent, and general onboarding versions.',
        fileUrl: '#',
        fileType: 'DOCX',
        fileSize: '58 KB',
      },
      {
        _id: 'block-1-8',
        blockType: 'quiz',
        title: 'Check-In: Community Onboarding',
        slug: 'check-in-community-onboarding',
        description: 'Confirm you know how to get your parishioners up and running.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-1-3',
            question: 'Where do you generate invite codes for your parishioners?',
            options: [
              'The Hallow mobile app',
              'The partner admin dashboard',
              'By emailing parishes@hallow.app',
              'The Hallow website',
            ],
            correctIndex: 1,
            explanation: 'Invite codes are generated and managed from the partner admin dashboard under the "Community" section.',
          },
          {
            _id: 'q-1-4',
            question: 'Which of these is the most effective channel for distributing invite codes to parishioners?',
            options: [
              'Posting the code on a public social media page',
              'Printing codes in the Sunday bulletin and announcing from the pulpit',
              'Sharing the code exclusively on the parish website',
              'Only sending via email to registered members',
            ],
            correctIndex: 1,
            explanation: 'Combining the Sunday bulletin with a verbal announcement from the pastor achieves the widest reach across all age groups.',
          },
        ],
      },
      // ── Section 4: Analytics ─────────────────────────────────
      {
        _id: 'block-1-9',
        blockType: 'video',
        title: 'Tracking Engagement & Analytics',
        slug: 'tracking-engagement-and-analytics',
        description: 'Understanding your dashboard metrics and how to measure community engagement.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 840,
      },
      {
        _id: 'block-1-10',
        blockType: 'quiz',
        title: 'Final Knowledge Check',
        slug: 'getting-started-final-knowledge-check',
        description: 'Put it all together — test your full understanding of the Hallow partnership.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-1-5',
            question: 'Which metric in the dashboard shows how many parishioners are praying daily?',
            options: [
              'Total Users',
              'Daily Active Users (DAU)',
              'Sessions This Week',
              'Invite Redemption Rate',
            ],
            correctIndex: 1,
            explanation: 'Daily Active Users (DAU) shows how many of your community members opened the app and prayed on any given day.',
          },
          {
            _id: 'q-1-6',
            question: 'Where can partners reach out for support?',
            options: [
              'support@hallow.com',
              'parishes@hallow.app',
              'The Hallow app chat feature',
              'Twitter / X',
            ],
            correctIndex: 1,
            explanation: 'Parish partners can reach the Hallow partner success team at parishes@hallow.app.',
          },
          {
            _id: 'q-1-7',
            question: 'A high Invite Redemption Rate means:',
            options: [
              'Many users have left the app',
              'A large portion of invited parishioners successfully created an account',
              'Your invite codes have expired',
              'Parishioners are spending more time in the app',
            ],
            correctIndex: 1,
            explanation: 'Invite Redemption Rate is the percentage of distributed codes that were used to create an account — higher is better.',
          },
        ],
      },
    ],
  },
  {
    _id: 'course-2',
    title: 'Leading Prayer in Your Community',
    slug: 'leading-prayer-in-your-community',
    description: 'Practical strategies for parish leaders and teachers to integrate Hallow into daily prayer routines, small groups, and liturgical seasons.',
    thumbnail: 'https://images.unsplash.com/photo-1553340731-5fa0221fde8d?w=800&q=80',
    category: 'Community Leadership',
    featured: true,
    publishedAt: '2024-02-01',
    blocks: [
      // ── Section 1: Prayer Culture ─────────────────────────────
      {
        _id: 'block-2-1',
        blockType: 'video',
        title: 'Building a Culture of Prayer',
        slug: 'building-a-culture-of-prayer',
        description: 'How to foster consistent prayer habits in your parish or school community.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 900,
      },
      {
        _id: 'block-2-2',
        blockType: 'quiz',
        title: 'Check-In: Prayer Culture',
        slug: 'check-in-prayer-culture',
        description: 'Quick check on the foundations of building a prayer culture.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-2-1',
            question: 'What is the single most important factor in building a sustained culture of prayer?',
            options: [
              'Buying premium subscriptions for everyone',
              'Consistent, visible leadership modeling prayer habits',
              'Running a social media campaign',
              'Setting up automated daily push notifications',
            ],
            correctIndex: 1,
            explanation: 'When parish leaders and pastors visibly participate in prayer — praying together, sharing reflections — the community follows. Leadership behavior is the strongest predictor of adoption.',
          },
          {
            _id: 'q-2-2',
            question: 'What does DAU/MAU ratio indicate about your community?',
            options: [
              'How many people downloaded the app',
              'The ratio of daily to monthly active users — a measure of habit strength',
              'Total prayer minutes logged',
              'Number of new sign-ups vs. cancellations',
            ],
            correctIndex: 1,
            explanation: 'A high DAU/MAU ratio means your community is praying consistently, not just occasionally — a strong indicator of habit formation.',
          },
        ],
      },
      // ── Section 2: Small Groups ───────────────────────────────
      {
        _id: 'block-2-3',
        blockType: 'video',
        title: 'Hallow for Small Groups',
        slug: 'hallow-for-small-groups',
        description: 'Curating Hallow content for Bible studies, faith-sharing groups, and RCIA.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 660,
      },
      {
        _id: 'block-2-4',
        blockType: 'file',
        title: 'Small Group Facilitator Guide',
        slug: 'small-group-facilitator-guide',
        description: 'A structured guide for leading small group prayer sessions using Hallow. Includes discussion questions and session outlines.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '890 KB',
      },
      {
        _id: 'block-2-5',
        blockType: 'quiz',
        title: 'Check-In: Small Groups',
        slug: 'check-in-small-groups',
        description: 'Test your understanding of running effective small group prayer with Hallow.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-2-3',
            question: 'Which Hallow feature is most effective for small faith-sharing groups?',
            options: [
              'The Daily Calm meditation',
              'Curated playlists shared via the partner dashboard',
              'The step-counting challenge',
              'Random content discovery',
            ],
            correctIndex: 1,
            explanation: 'Curated playlists let you select and share specific Hallow content tailored to your group\'s theme or season.',
          },
          {
            _id: 'q-2-4',
            question: 'For an RCIA group, which content type in Hallow is most appropriate to use as a session opener?',
            options: [
              'A long-form audio retreat (60+ minutes)',
              'A short guided prayer or Scripture reflection (5–10 minutes)',
              'A podcast-style discussion on theology',
              'A sleep meditation',
            ],
            correctIndex: 1,
            explanation: 'Short guided prayers or Scripture reflections are ideal for opening small group sessions — they center the group without consuming the whole meeting time.',
          },
        ],
      },
      // ── Section 3: Seasonal Campaigns ────────────────────────
      {
        _id: 'block-2-6',
        blockType: 'video',
        title: 'Seasonal Prayer Campaigns',
        slug: 'seasonal-prayer-campaigns',
        description: 'Running successful Advent, Lent, and other liturgical season challenges.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 780,
      },
      {
        _id: 'block-2-7',
        blockType: 'quiz',
        title: 'Final Knowledge Check',
        slug: 'community-leadership-final-knowledge-check',
        description: 'Bring it all together — campaigns, metrics, and community strategy.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-2-5',
            question: 'When is the best time to launch a Lent prayer campaign with your community?',
            options: [
              'Ash Wednesday itself',
              '4–6 weeks before Ash Wednesday',
              'The Sunday before Lent',
              'During Holy Week',
            ],
            correctIndex: 1,
            explanation: 'Launching 4–6 weeks ahead gives you time to build awareness, distribute invite codes, and generate momentum before Lent begins.',
          },
          {
            _id: 'q-2-6',
            question: 'Which combination of promotion channels reaches the broadest parish audience during Advent?',
            options: [
              'Email only',
              'Instagram and Facebook only',
              'Sunday bulletin, pulpit announcement, and parish email list',
              'Parish website and app notification',
            ],
            correctIndex: 2,
            explanation: 'Reaching parishioners through multiple touchpoints — especially the in-person Sunday announcement — dramatically increases participation.',
          },
          {
            _id: 'q-2-7',
            question: 'What does a declining DAU trend after the first two weeks of Lent typically indicate?',
            options: [
              'The campaign was a complete failure',
              'Normal drop-off after initial excitement — a re-engagement push is needed',
              'Users have completed the full Lent journey',
              'The invite codes have expired',
            ],
            correctIndex: 1,
            explanation: 'Engagement naturally dips after the launch excitement fades. A mid-campaign re-engagement push (bulletin reminder, pastor mention) typically recovers momentum.',
          },
        ],
      },
    ],
  },
  {
    _id: 'course-3',
    title: 'Hallow in Catholic Schools',
    slug: 'hallow-in-catholic-schools',
    description: 'Designed specifically for Catholic school educators. Integrate Hallow into your daily schedule, religious education classes, and school-wide prayer initiatives.',
    thumbnail: 'https://images.unsplash.com/photo-1658786840545-fff53eee1e86?w=800&q=80',
    category: 'Education',
    featured: false,
    publishedAt: '2024-03-10',
    blocks: [
      // ── Section 1: Educator Overview ─────────────────────────
      {
        _id: 'block-3-1',
        blockType: 'video',
        title: 'Introduction for Educators',
        slug: 'introduction-for-educators',
        description: 'An overview of Hallow\'s school partnership features and the educator dashboard.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 540,
      },
      {
        _id: 'block-3-2',
        blockType: 'quiz',
        title: 'Check-In: Educator Overview',
        slug: 'check-in-educator-overview',
        description: 'Make sure you have the fundamentals of the school partnership.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-3-1',
            question: 'Which grade levels is Hallow appropriate for?',
            options: [
              'High school only (9–12)',
              'Middle and high school (6–12)',
              'All K–12 grades with age-appropriate content',
              'College students only',
            ],
            correctIndex: 2,
            explanation: 'Hallow offers content appropriate for all K–12 students. The educator dashboard lets you filter and assign content by age group.',
          },
          {
            _id: 'q-3-2',
            question: 'What separates the school educator dashboard from the parish partner dashboard?',
            options: [
              'The school dashboard has a different color scheme',
              'The school dashboard includes classroom and grade-level groupings and age-filtered content',
              'They are identical — same features for all partner types',
              'The school dashboard only works on desktop browsers',
            ],
            correctIndex: 1,
            explanation: 'The educator dashboard is tailored for school workflows — it organizes users by classroom/grade and surfaces age-appropriate content recommendations.',
          },
        ],
      },
      // ── Section 2: Classroom Integration ─────────────────────
      {
        _id: 'block-3-3',
        blockType: 'video',
        title: 'Classroom Integration Strategies',
        slug: 'classroom-integration-strategies',
        description: 'Practical ways to use Hallow in religion class, homeroom, and beyond.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 840,
      },
      {
        _id: 'block-3-4',
        blockType: 'file',
        title: 'Classroom Integration Guide',
        slug: 'classroom-integration-guide',
        description: 'A printable guide for teachers covering how to integrate Hallow into daily classroom prayer, grades K-12.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '1.1 MB',
      },
      {
        _id: 'block-3-5',
        blockType: 'file',
        title: 'Weekly Prayer Schedule Template',
        slug: 'weekly-prayer-schedule-template',
        description: 'An editable Word document for building a weekly classroom prayer schedule around Hallow content.',
        fileUrl: '#',
        fileType: 'DOCX',
        fileSize: '72 KB',
      },
      {
        _id: 'block-3-6',
        blockType: 'quiz',
        title: 'Check-In: Classroom Integration',
        slug: 'check-in-classroom-integration',
        description: 'Confirm you\'re ready to bring Hallow into your classroom.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-3-3',
            question: 'What is the recommended daily prayer window for classroom Hallow use?',
            options: [
              '30–45 minutes at the start of religion class',
              '5–10 minutes at the start or end of homeroom',
              'A full free period once a week',
              'Only during Mass preparation',
            ],
            correctIndex: 1,
            explanation: 'Short, consistent daily sessions (5–10 minutes) build stronger prayer habits than infrequent longer sessions. Homeroom is the ideal slot.',
          },
          {
            _id: 'q-3-4',
            question: 'When assigning Hallow content to elementary students (K-5), you should:',
            options: [
              'Use the same content as high school students — it\'s all appropriate',
              'Filter by age group in the educator dashboard to surface K-5 appropriate content',
              'Only use the "Sleep Meditations" playlist',
              'Ask students to find their own content in the app',
            ],
            correctIndex: 1,
            explanation: 'The educator dashboard\'s age filter ensures you only surface content that is appropriate and engaging for your grade level.',
          },
        ],
      },
      // ── Section 3: Reporting ──────────────────────────────────
      {
        _id: 'block-3-7',
        blockType: 'video',
        title: 'Student Engagement & Reporting',
        slug: 'student-engagement-and-reporting',
        description: 'Using the school dashboard to monitor participation and share reports with administration.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 600,
      },
      {
        _id: 'block-3-8',
        blockType: 'quiz',
        title: 'Final Knowledge Check',
        slug: 'catholic-schools-final-knowledge-check',
        description: 'Confirm your full readiness to implement Hallow across your school.',
        passingScore: 80,
        questions: [
          {
            _id: 'q-3-5',
            question: 'How do you share a progress report with your school administration?',
            options: [
              'Email parishes@hallow.app and request a report',
              'Export directly from the school dashboard as a PDF or CSV',
              'Screenshot the dashboard and share manually',
              'Ask Hallow\'s support team to generate one',
            ],
            correctIndex: 1,
            explanation: 'The school dashboard has a built-in export feature that generates PDF and CSV reports for sharing with administrators and board members.',
          },
          {
            _id: 'q-3-6',
            question: 'Which metric best demonstrates Hallow\'s impact to a school principal?',
            options: [
              'Total app downloads school-wide',
              'Average daily prayer sessions per student over a semester',
              'Number of students who rated the app 5 stars',
              'How many students followed Hallow on social media',
            ],
            correctIndex: 1,
            explanation: 'Consistent daily engagement over time — not one-time actions — is the metric that demonstrates genuine habit formation and spiritual impact.',
          },
          {
            _id: 'q-3-7',
            question: 'A teacher notices student engagement dropped in week three of an Advent challenge. What should they do?',
            options: [
              'End the challenge early and move on',
              'Give students extra credit for completing sessions to re-engage them',
              'Do a brief in-class reflection and re-announce the challenge with pastoral enthusiasm',
              'Switch to a different prayer app',
            ],
            correctIndex: 2,
            explanation: 'Re-anchoring the challenge with a classroom moment of shared prayer and visible teacher enthusiasm typically restores momentum.',
          },
        ],
      },
    ],
  },
  {
    _id: 'course-4',
    title: 'Advanced Partnership Features',
    slug: 'advanced-partnership-features',
    description: 'Deep dive into advanced features for experienced partners: custom content channels, bulk user management, API integrations, and white-label options.',
    thumbnail: 'https://images.unsplash.com/photo-1593112038458-246525299766?w=800&q=80',
    category: 'Advanced',
    featured: false,
    publishedAt: '2024-04-05',
    blocks: [
      // ── Section 1: Content Channels ───────────────────────────
      {
        _id: 'block-4-1',
        blockType: 'video',
        title: 'Custom Content Channels',
        slug: 'custom-content-channels',
        description: 'Create and manage custom prayer channels for your community.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 960,
      },
      {
        _id: 'block-4-2',
        blockType: 'quiz',
        title: 'Check-In: Content Channels',
        slug: 'check-in-content-channels',
        description: 'Confirm your understanding of custom channel setup.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-4-1',
            question: 'What can you include in a custom Hallow content channel?',
            options: [
              'Only audio meditations recorded by Hallow\'s team',
              'A curated selection of existing Hallow content plus your own uploaded audio',
              'Only third-party podcasts',
              'Text-only prayer guides with no audio',
            ],
            correctIndex: 1,
            explanation: 'Custom channels support both curated Hallow library content and partner-uploaded audio, giving you full control over your community\'s prayer experience.',
          },
          {
            _id: 'q-4-2',
            question: 'Who can see a custom content channel you create?',
            options: [
              'All Hallow users globally',
              'Only users who joined via your partner invite code',
              'Only Hallow employees',
              'Anyone who searches for it in the app',
            ],
            correctIndex: 1,
            explanation: 'Custom channels are scoped to your partner community — only members who joined through your invite code will see and access the channel.',
          },
        ],
      },
      // ── Section 2: User Management ────────────────────────────
      {
        _id: 'block-4-3',
        blockType: 'video',
        title: 'Bulk User Management',
        slug: 'bulk-user-management',
        description: 'Import, manage, and organize large numbers of users efficiently.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 720,
      },
      {
        _id: 'block-4-4',
        blockType: 'quiz',
        title: 'Check-In: User Management',
        slug: 'check-in-user-management',
        description: 'Test your knowledge of managing large user groups.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-4-3',
            question: 'What is the most efficient way to onboard 500+ users at once?',
            options: [
              'Send individual invites one by one',
              'Use the bulk CSV import in the admin dashboard',
              'Ask Hallow support to import them manually',
              'Create a shared invite link and post it publicly',
            ],
            correctIndex: 1,
            explanation: 'The bulk CSV import tool in the admin dashboard lets you upload a spreadsheet of users and send invites in a single action.',
          },
          {
            _id: 'q-4-4',
            question: 'When should you use user groups within the admin dashboard?',
            options: [
              'Only for users with premium subscriptions',
              'To organize users by ministry, grade, or location for targeted reporting and content',
              'Groups are only for schools, not parishes',
              'Groups are only needed when you have 1,000+ users',
            ],
            correctIndex: 1,
            explanation: 'User groups let you segment your community (e.g., by ministry team or school grade) so you can track engagement and surface relevant content per segment.',
          },
        ],
      },
      // ── Section 3: SSO & API ──────────────────────────────────
      {
        _id: 'block-4-5',
        blockType: 'video',
        title: 'SSO & API Integration',
        slug: 'sso-and-api-integration',
        description: 'Connecting Hallow with your school information system or parish management software.',
        videoProvider: 'youtube',
        videoId: 'dQw4w9WgXcQ',
        duration: 1080,
      },
      {
        _id: 'block-4-6',
        blockType: 'file',
        title: 'API Documentation',
        slug: 'api-documentation',
        description: 'Full technical documentation for the Hallow Partner API, including authentication, endpoints, and example requests.',
        fileUrl: '#',
        fileType: 'PDF',
        fileSize: '3.4 MB',
      },
      {
        _id: 'block-4-7',
        blockType: 'quiz',
        title: 'Final Knowledge Check',
        slug: 'advanced-features-final-knowledge-check',
        description: 'Verify your full understanding of Hallow\'s advanced integration and management features.',
        passingScore: 75,
        questions: [
          {
            _id: 'q-4-5',
            question: 'What authentication method does the Hallow Partner API support?',
            options: [
              'Basic username/password',
              'OAuth 2.0 and API key authentication',
              'Cookie-based sessions only',
              'No authentication required',
            ],
            correctIndex: 1,
            explanation: 'The Hallow Partner API supports both OAuth 2.0 for user-level access and API key authentication for server-to-server integrations.',
          },
          {
            _id: 'q-4-6',
            question: 'What is SSO (Single Sign-On) used for in a school context?',
            options: [
              'Allowing students to pay for Hallow with a school account',
              'Letting students log into Hallow automatically using their existing school Google or Microsoft account',
              'Creating a shared Hallow account all students use simultaneously',
              'Exporting student data to a government database',
            ],
            correctIndex: 1,
            explanation: 'SSO lets students sign into Hallow using the same credentials they already use for school systems (Google Workspace, Microsoft 365), eliminating password friction.',
          },
          {
            _id: 'q-4-7',
            question: 'Which API endpoint would you use to automatically provision new student accounts at the start of each school year?',
            options: [
              'GET /community/stats',
              'POST /users/bulk',
              'DELETE /users/archive',
              'PATCH /channels/update',
            ],
            correctIndex: 1,
            explanation: 'POST /users/bulk accepts a JSON array of user objects and provisions accounts in a single request — ideal for annual school enrollment automation.',
          },
        ],
      },
    ],
  },
];

export const mockWebinars: Webinar[] = [
  {
    _id: 'webinar-1',
    title: 'Spring Parish Kickoff: Maximizing Hallow This Lent',
    slug: 'spring-parish-kickoff-maximizing-hallow-this-lent',
    description: 'Join our partnership team for a live walkthrough of the best Hallow content for Lent 2025. We\'ll cover featured meditations, the 40-day challenge, and how to run a parish-wide campaign.',
    thumbnail: 'https://images.unsplash.com/photo-1755643124762-7b69899be8d6?w=800&q=80',
    presenter: 'Maria Santos, Partnership Success Manager',
    scheduledAt: '2026-04-15T18:00:00Z',
    status: 'upcoming',
    registrationUrl: 'https://hallow.com/webinar-register',
    duration: 60,
    tags: ['Lent', 'Parish', 'Seasonal'],
    featured: true,
    spotlight: true,
  },
  {
    _id: 'webinar-2',
    title: 'New Partner Orientation — Q2 2026',
    slug: 'new-partner-orientation-q2-2026',
    description: 'A live onboarding session for partners who joined in the last 90 days. Get your questions answered and connect with other new partners.',
    thumbnail: 'https://images.unsplash.com/photo-1560698831-07984c110e4d?w=800&q=80',
    presenter: 'James O\'Brien, Head of Partner Success',
    scheduledAt: '2026-04-22T19:00:00Z',
    status: 'upcoming',
    registrationUrl: 'https://hallow.com/webinar-register',
    duration: 90,
    tags: ['Onboarding', 'New Partners'],
    featured: false,
  },
  {
    _id: 'webinar-3',
    title: 'Year in Review: Partner Success Stories 2025',
    slug: 'year-in-review-partner-success-stories-2025',
    description: 'Highlights from our top partner communities in 2025 — hear directly from parishes and schools that achieved remarkable growth in prayer engagement.',
    thumbnail: 'https://images.unsplash.com/photo-1676200259384-b2900d8478a3?w=800&q=80',
    presenter: 'Multiple Presenters',
    scheduledAt: '2025-12-10T19:00:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456789',
    duration: 75,
    tags: ['Case Studies', 'Community', 'Annual Review'],
    featured: true,
  },
  {
    _id: 'webinar-4',
    title: 'Advent Planning Workshop',
    slug: 'advent-planning-workshop',
    description: 'Everything you need to run a successful Advent prayer campaign. Templates, best practices, and a live Q&A with the content team.',
    thumbnail: 'https://images.unsplash.com/photo-1763630239158-d032e93d525b?w=800&q=80',
    presenter: 'Fr. Timothy Walsh & Partnership Team',
    scheduledAt: '2025-10-20T18:30:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456790',
    duration: 90,
    tags: ['Advent', 'Seasonal', 'Parish'],
    featured: false,
  },
  {
    _id: 'webinar-5',
    title: 'Hallow for Catholic Schools: Back to School Edition',
    slug: 'hallow-for-catholic-schools-back-to-school',
    description: 'Preparing your school community for a new year of prayer with Hallow. Covers classroom setup, student accounts, and the new educator portal.',
    thumbnail: 'https://images.unsplash.com/photo-1465848059293-208e11dfea17?w=800&q=80',
    presenter: 'Sarah Kim, Education Partnerships Lead',
    scheduledAt: '2025-08-15T17:00:00Z',
    status: 'past',
    recordingUrl: 'https://vimeo.com/123456791',
    duration: 60,
    tags: ['Schools', 'Education', 'Onboarding'],
    featured: false,
  },
];

export const mockResources: Resource[] = [
  {
    _id: 'resource-1',
    title: 'Partner Welcome Guide',
    slug: 'partner-welcome-guide',
    description: 'Your complete reference for getting started as a Hallow partner. Covers account setup, key contacts, and your first 30 days.',
    category: 'documentation',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-01-10',
    fileType: 'PDF',
  },
  {
    _id: 'resource-2',
    title: 'Parish Bulletin Insert Templates',
    slug: 'parish-bulletin-insert-templates',
    description: 'Ready-to-use bulletin inserts for announcing Hallow to your parishioners. Available in standard bulletin sizes.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-01-20',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-3',
    title: 'Lent 2026 Campaign Kit',
    slug: 'lent-2026-campaign-kit',
    description: 'Complete campaign materials for Lent 2026 including social media graphics, bulletin inserts, email templates, and a promotional video.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2026-01-15',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-4',
    title: 'Hallow x RCIA: A Curriculum Guide',
    slug: 'hallow-rcia-curriculum-guide',
    description: 'A semester-long curriculum guide for RCIA directors incorporating Hallow meditations, Scripture, and prayer practices.',
    category: 'teacher-planning',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-01',
    fileType: 'PDF',
  },
  {
    _id: 'resource-5',
    title: 'Admin Dashboard User Manual',
    slug: 'admin-dashboard-user-manual',
    description: 'Detailed documentation for the partner admin dashboard. Covers user management, analytics, content settings, and billing.',
    category: 'technical-guides',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-02-15',
    fileType: 'PDF',
  },
  {
    _id: 'resource-6',
    title: 'How to Talk About Hallow: Key Messages',
    slug: 'how-to-talk-about-hallow-key-messages',
    description: 'Approved talking points, FAQs, and messaging guidance for introducing Hallow to your community.',
    category: 'educational-content',
    resourceType: 'file',
    file: '#',
    featured: true,
    publishedAt: '2024-02-01',
    fileType: 'PDF',
  },
  {
    _id: 'resource-7',
    title: 'Classroom Prayer Integration Guide',
    slug: 'classroom-prayer-integration-guide',
    description: 'For Catholic school educators: structured guides for incorporating Hallow into daily classroom prayer routines, grades K-12.',
    category: 'teacher-planning',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-15',
    fileType: 'PDF',
  },
  {
    _id: 'resource-8',
    title: 'API & SSO Integration Documentation',
    slug: 'api-sso-integration-documentation',
    description: 'Technical documentation for connecting Hallow to your school information system (SIS) or parish management software via SSO or API.',
    category: 'technical-guides',
    resourceType: 'link',
    externalUrl: '#',
    featured: false,
    publishedAt: '2024-04-01',
    fileType: 'LINK',
  },
  {
    _id: 'resource-9',
    title: 'Social Media Asset Pack',
    slug: 'social-media-asset-pack',
    description: 'High-resolution social media graphics, story templates, and profile overlays for promoting Hallow on your parish or school accounts.',
    category: 'marketing-materials',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-01-25',
    fileType: 'ZIP',
  },
  {
    _id: 'resource-10',
    title: 'The Science of Prayer: A Discussion Guide',
    slug: 'science-of-prayer-discussion-guide',
    description: 'Educational resource exploring the research behind prayer and mindfulness. Great for adult faith formation groups and high school theology classes.',
    category: 'educational-content',
    resourceType: 'file',
    file: '#',
    featured: false,
    publishedAt: '2024-03-20',
    fileType: 'PDF',
  },
];
